USE [SISE_NEW]
GO

		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(1,4639,'SENTENCIA') 
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(2,2085, 'RESOLUCION PLAZO CONSTITUCIONAL')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(2,1910,'RESOLUCION QUE PONE FIN AL PROCEDIMIENTO')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(2,2330,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(4,3877, 'SENTENCIA')  
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(18,5534, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(19,3075, 'OPINION JUEZ')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(58,8217, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(67,16990, 'SIPE_Declaratoria Extinción Pena')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(67,17384, 'INC_Declaratoria Extinción Pena')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(68,9700, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(71,10473, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(6,5863, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(9,5713, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(109,18377, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(10,302, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(11,1226, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(12,91,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(13,2923,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(14,1755,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(15,616,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(15,688,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(16,1010,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(17,834, 'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(20,4291,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(23,1425,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(24,1580,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(25,512,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(26,4902,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(28,4391,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(55,4333,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(56,4362,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(27,7227,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(44,1317,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(45,2803,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(69,10144,'SENTENCIA')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,128382, 'Causa Penal_Audiencia Privada_Egreso')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,12550, 'Causa Penal_Audiencia Privada_Egreso')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,11947, 'Tecnicas Investigacion_Actos de Investigacion_Egreso')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,15539, 'Tecnicas Investigacion_Ingreso a lugar sin autorizacion judicial_Egreso')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,13016, 'Tecnicas Investigacion_Providencias precautorias_Egreso')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,13146, 'Tecnicas Investigacion_Prueba anticipada_Egreso')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,13547, 'Procedimiento de Ejecución_Solicitud de inicio de Procedimiento de Ejecución (SIPE)_EgresoResFin')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,13607, 'Procedimiento de Ejecución_Solicitud de Incidente_EgresoResFin')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,16006, 'Procedimiento de Ejecución_Controversia_EgresoResFin')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,15751, 'Procedimiento de Ejecución_Ejecucion Medida Cautelar_EgresoResFin')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,14181, 'Impugnacion_Ejecucion Medida Cautelar_EgresoResFin')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,17459, 'DeclaratoriaAbandono_EgresoDecisionAdoptada')
		insert into SISE_NEW.SISE3.CatSentidoSentenciaXCatTipoAsunto values(74,14815, 'Medidas Cautelares__Egreso')
GO


