trigger:
  branches:
    include:
    - QA
  paths:
    include:
    - Codigo/CJF.Sgcpj.Judicatura/src/Proyectos/**/*
    - Codigo/CJF.Sgcpj.Judicatura/src/Comunes/**/*

pool: 'SISE-CICD-QA'
  
variables:
  tag: '$(Build.BuildId)'
  pathBuildContext: '$(Build.SourcesDirectory)/Codigo/CJF.Sgcpj.Judicatura/src/Proyectos/Proyectos.Functions'
  env: 'qa'
  buildConfiguration: 'Release'

stages:
- stage: Backend
  jobs:
  - job: CD
    workspace:
      clean: all # what to clean up before the job runs
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'SC-QA-SISE'
        KeyVaultName: 'kv-ussc-qa-sise'
        SecretsFilter: '*'
        RunAsPreJob: false
      displayName: 'Get secrets'  
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 'x'
        checkLatest: true
      displayName: 'Nuget tool install'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(pathBuildContext)/Proyectos.Functions.csproj'
        feedsToUse: 'select'
      displayName: 'dotnet restore'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '$(pathBuildContext)/Proyectos.Functions.csproj'
      displayName: 'dotnet build'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(pathBuildContext)/Proyectos.Functions.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
      displayName: 'Publish the project - $(buildConfiguration)'  
    - task: AzureAppServiceSettings@1
      inputs:
        azureSubscription: 'SC-QA-SISE'
        appName: 'func-ussc-qa-sise-proyectos'
        resourceGroupName: 'RG-USSC-QA-SISE'
        appSettings: |
          [
             {
              "name": "AppConfigurationConnStr",
              "value": "$(AppConfigurationConnStr)",
              "slotSetting": false
             },
             {
              "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
              "value": "$(AppInsightsInstrumentationKey)",
              "slotSetting": false
             },
             {
              "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
              "value": "$(AppInsightsConnStr)",
              "slotSetting": false
             }
          ]
      displayName: 'Deploy App Settings'
    - task: AzureFunctionApp@2
      inputs:
        connectedServiceNameARM: 'SC-QA-SISE'
        appType: 'functionAppLinux'
        appName: 'func-ussc-qa-sise-proyectos'
        package: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)/Proyectos.Functions.zip'
        runtimeStack: 'DOTNET|6.0'
        deploymentMethod: 'auto'
      displayName: 'Deploy to Function App'    

  