FROM ubuntu:22.04 AS build
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

WORKDIR /app

COPY . .

RUN npm install -g @vue/cli
RUN npm install -g @quasar/cli
RUN npm install

EXPOSE 9000

CMD ["quasar", "dev"]
